220905
./www/log/220905.wik
SVGACT - FEATURE
1 button (Line mode) is implemented // TDDTEST2 FTR

SVGACT - TDD TESTING
Add TDD Testing support

SVGACT - TDD TESTING - URL
?tdd=<#>
?tddf=<#>

SVGACT - TDD TESTING - URL - RUN FIRST (0TH) TEST AND (STOP) FREEZE
file:///k/www/svg/ActSvg.html?tddf=0

SVGACT - TDD TESTING - URL - RUN FIRST (0TH) TEST AND CONTINUE
file:///k/www/svg/ActSvg.html?tdd=0

SVGACT - TDD TESTS
test0 - rect move x should move subselected text
test1 - click whitespace beyond text should select surrounding rect
test2 - mode two click twice creates line

./adm/log/220905.wik
AUTO-ASSIGN DATED-FILENAMES TO UNDATED CHANGELOG
WIK FILES THAT ARE NAMED STAGE

temp filesys naming: STAGE.wik
auto-converted to: {YYMMDD}.wik

# /k/{SUBPATH}/log/STAGE.wik
stage-changelog
# /k/{SUBPATH}/log/{YYMMDD}.wik

diff --git a/adm/bin/stage-changelog b/adm/bin/stage-changelog
--- a/adm/bin/stage-changelog
+++ b/adm/bin/stage-changelog
@@ -3,9 +3,16 @@
 nl=$'\n'
 msg="${nl}$(date +%y%m%d)${nl}${nl}"
 cd /k
-for f in `find . -name "$(date +%y%m%d).wik"`;
+for f in `find . -name "STAGE.wik"`;
 do
-	git add "$f"
-	msg="${msg}${f}${nl}$(cat $f)${nl}${nl}"
+    dt=$(date +%y%m%d)
+    fn=$(echo "$f" | sed "s/STAGE/$dt/g")
+    if [[ -e "$fn" ]]; then
+        echo "Error: ${fn} file exists!" 1>&2
+        exit 1;
+    fi
+    mv "$f" "$fn"
+    git add "$fn"
+    msg="${msg}${fn}${nl}$(cat $fn)${nl}${nl}"
 done
 echo "$msg"
